// swift-tools-version: 5.7
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
	name: "WebRTC",
	platforms: [
		.iOS(.v15),
		.macOS(.v12),
	],
	products: [
		.library(
			name: "WebRTC",
			targets: ["WebRTC"]),
	],
	dependencies: [
		.package(url: "https://github.com/ronnyf/abseil-cpp", .upToNextMinor(from: "1.0.5")),
		.package(url: "https://github.com/ronnyf/libyuv.git", .upToNextMajor(from: "1.0.2")),
		.package(url: "https://github.com/ronnyf/protobuf.git", .upToNextMajor(from: "4.25.0")),
		.package(url: "https://github.com/ronnyf/libopus.git", .upToNextMajor(from: "1.4.0")),
		.package(url: "https://github.com/ronnyf/libsrtp.git", .upToNextMajor(from: "2.2.0")),
		.package(url: "https://github.com/ronnyf/rnnoise.git", .upToNextMajor(from: "1.0.0")),
		.package(url: "https://github.com/ronnyf/crc32c.git", .upToNextMajor(from: "1.1.0")),
		.package(url: "https://github.com/ronnyf/boringssl.git", .upToNextMajor(from: "1.0.0")),
		.package(url: "https://github.com/ronnyf/jsoncpp.git", .upToNextMinor(from: "1.9.0")),
	],
	targets: [
		.binaryTarget(name: "CoreRTC", path: "dist/CoreRTC.xcframework"),
		.target(
			name: "WebRTC",
			dependencies: [
				.target(name: "CoreRTC"),
				.product(name: "absl_base", package: "abseil-cpp"),
				.product(name: "libyuv", package: "libyuv"),
			],
			path: ".",
			sources: [
				"sdk/objc/native/src/objc_audio_device.mm",
				"sdk/objc/components/renderer/metal/RTCMTLNV12Renderer.mm",
				"sdk/objc/api/peerconnection/RTCMediaStream.mm",
				"sdk/objc/native/src/objc_video_renderer.mm",
				"sdk/objc/components/renderer/metal/RTCMTLI420Renderer.mm",
				"sdk/objc/helpers/UIDevice+RTCDevice.m",
				"sdk/objc/api/video_codec/RTCVideoEncoderVP8.mm",
				"sdk/objc/api/peerconnection/RTCFileLogger.mm",
				"sdk/objc/api/peerconnection/RTCVideoCodecInfo+Private.mm",
				"sdk/objc/native/src/objc_video_encoder_factory.mm",
				"sdk/objc/api/peerconnection/RTCAudioSource.mm",
				"sdk/objc/api/peerconnection/RTCConfiguration.mm",
				"sdk/objc/api/video_codec/RTCWrappedNativeVideoEncoder.mm",
				"sdk/objc/api/peerconnection/RTCLegacyStatsReport.mm",
				"sdk/objc/api/peerconnection/RTCDataChannel.mm",
				"sdk/objc/api/video_codec/RTCVideoDecoderVP8.mm",
				"sdk/objc/api/peerconnection/RTCAudioTrack.mm",
				"sdk/objc/api/video_codec/RTCVideoCodecConstants.mm",
				"sdk/objc/components/video_codec/RTCVideoEncoderH264.mm",
				"sdk/objc/api/peerconnection/RTCMetricsSampleInfo.mm",
				"sdk/objc/api/peerconnection/RTCRtpCodecParameters.mm",
				"sdk/objc/api/video_codec/RTCVideoDecoderAV1.mm",
				"sdk/objc/components/video_codec/video_codec_helpers.cc",
				"sdk/objc/helpers/RTCDispatcher.m",
				"sdk/objc/native/api/video_frame_buffer.mm",
				"sdk/objc/api/video_codec/RTCWrappedNativeVideoDecoder.mm",
				"sdk/objc/api/peerconnection/RTCVideoSource.mm",
				"sdk/objc/api/logging/RTCCallbackLogger.mm",
				"sdk/objc/api/peerconnection/RTCVideoTrack.mm",
				"sdk/objc/components/renderer/opengl/RTCEAGLVideoView.m",
				"sdk/objc/base/RTCVideoCodecInfo.m",
				"sdk/objc/components/video_frame_buffer/RTCCVPixelBuffer.mm",
				"sdk/objc/components/renderer/opengl/RTCShader.mm",
				"sdk/objc/native/src/objc_video_frame.mm",
				"sdk/objc/components/renderer/opengl/RTCDisplayLinkTimer.m",
				"sdk/objc/api/video_codec/RTCVideoDecoderVP9.mm",
				"sdk/objc/api/peerconnection/RTCRtpSender.mm",
				"sdk/objc/native/src/objc_frame_buffer.mm",
				"sdk/objc/api/peerconnection/RTCPeerConnectionFactoryOptions.mm",
				"sdk/objc/api/peerconnection/RTCIceCandidate.mm",
				"sdk/objc/components/video_codec/RTCVideoDecoderFactoryH264.m",
				"sdk/objc/api/peerconnection/RTCEncodedImage+Private.mm",
				"sdk/objc/components/video_codec/RTCDefaultVideoDecoderFactory.m",
				"sdk/objc/api/peerconnection/RTCTracing.mm",
				"sdk/objc/api/RTCVideoRendererAdapter.mm",
				"sdk/objc/native/api/native_network_monitor_factory.mm",
				"sdk/objc/api/peerconnection/RTCSessionDescription.mm",
				"sdk/objc/native/api/video_renderer.mm",
				"sdk/objc/native/api/objc_to_native_video_encoder_factory.mm",
				"sdk/objc/native/src/objc_audio_device_delegate.mm",
				"sdk/objc/api/peerconnection/RTCPeerConnection.mm",
				"sdk/objc/components/renderer/opengl/RTCNV12TextureCache.m",
				"sdk/objc/components/video_codec/nalu_rewriter.cc",
				"sdk/objc/helpers/AVCaptureSession+DevicePosition.m",
				"sdk/objc/native/api/objc_audio_device_module.mm",
				"sdk/objc/native/api/video_capturer.mm",
				"sdk/objc/api/video_codec/RTCVideoEncoderAV1.mm",
				"sdk/objc/api/peerconnection/RTCIceCandidateErrorEvent.mm",
				"sdk/objc/api/peerconnection/RTCMediaStreamTrack.mm",
				"sdk/objc/api/peerconnection/RTCRtcpParameters.mm",
				"sdk/objc/api/peerconnection/RTCPeerConnectionFactoryBuilder.mm",
				"sdk/objc/api/peerconnection/RTCIceServer.mm",
				"sdk/objc/components/renderer/metal/RTCMTLNSVideoView.m",
				"sdk/objc/base/RTCEncodedImage.m",
				"sdk/objc/api/peerconnection/RTCRtpTransceiver.mm",
				"sdk/objc/api/peerconnection/RTCRtpParameters.mm",
				"sdk/objc/api/peerconnection/RTCPeerConnectionFactory.mm",
				"sdk/objc/components/video_codec/RTCVideoDecoderH264.mm",
				"sdk/objc/native/src/objc_video_track_source.mm",
				"sdk/objc/native/src/objc_video_decoder_factory.mm",
				"sdk/objc/api/peerconnection/RTCDataChannelConfiguration.mm",
				"sdk/objc/api/peerconnection/RTCFieldTrials.mm",
				"sdk/objc/api/peerconnection/RTCDtmfSender.mm",
				"sdk/objc/native/api/audio_device_module.mm",
				"sdk/objc/components/video_codec/UIDevice+H264Profile.mm",
				"sdk/objc/components/video_codec/RTCH264ProfileLevelId.mm",
				"sdk/objc/api/peerconnection/RTCCertificate.mm",
				"sdk/objc/native/api/objc_to_native_video_decoder_factory.mm",
				"sdk/objc/base/RTCVideoCapturer.m",
				"sdk/objc/api/peerconnection/RTCStatisticsReport.mm",
				"sdk/objc/components/renderer/opengl/RTCDefaultShader.mm",
				"sdk/objc/base/RTCVideoFrame.mm",
				"sdk/objc/components/video_codec/RTCDefaultVideoEncoderFactory.m",
				"sdk/objc/api/peerconnection/RTCPeerConnectionFactoryBuilder+DefaultComponents.mm",
				"sdk/objc/base/RTCVideoEncoderSettings.m",
				"sdk/objc/base/RTCLogging.mm",
				"sdk/objc/components/video_codec/RTCCodecSpecificInfoH264.mm",
				"sdk/objc/helpers/NSString+StdString.mm",
				"sdk/objc/native/src/objc_network_monitor.mm",
				"sdk/objc/components/renderer/opengl/RTCI420TextureCache.mm",
				"sdk/objc/api/video_codec/RTCVideoEncoderVP9.mm",
				"sdk/objc/api/peerconnection/RTCRtpReceiver.mm",
				"sdk/objc/api/video_frame_buffer/RTCNativeI420Buffer.mm",
				"sdk/objc/components/capturer/RTCFileVideoCapturer.m",
				"sdk/objc/base/RTCVideoEncoderQpThresholds.m",
				"sdk/objc/api/peerconnection/RTCVideoEncoderSettings+Private.mm",
				"sdk/objc/native/api/ssl_certificate_verifier.mm",
				"sdk/objc/components/network/RTCNetworkMonitor.mm",
				"sdk/objc/native/api/native_to_objc_video_frame.mm",
				"sdk/objc/api/peerconnection/RTCCryptoOptions.mm",
				"sdk/objc/api/peerconnection/RTCSSLAdapter.mm",
				"sdk/objc/components/renderer/metal/RTCMTLRGBRenderer.mm",
				"sdk/objc/api/video_frame_buffer/RTCNativeMutableI420Buffer.mm",
				"sdk/objc/components/renderer/metal/RTCMTLRenderer.mm",
				"sdk/objc/api/peerconnection/RTCRtpHeaderExtension.mm",
				"sdk/objc/components/capturer/RTCCameraVideoCapturer.m",
				"sdk/objc/api/peerconnection/RTCMetrics.mm",
				"sdk/objc/api/peerconnection/RTCMediaSource.mm",
				"sdk/objc/components/video_codec/RTCVideoEncoderFactoryH264.m",
				"sdk/objc/helpers/RTCCameraPreviewView.m",
				"sdk/objc/api/peerconnection/RTCPeerConnection+DataChannel.mm",
				"sdk/objc/components/renderer/metal/RTCMTLVideoView.m",
				"sdk/objc/api/peerconnection/RTCMediaConstraints.mm",
				"sdk/objc/api/peerconnection/RTCRtpEncodingParameters.mm",
				"sdk/objc/api/peerconnection/RTCPeerConnection+Stats.mm",
			],
			publicHeadersPath: "include",
			cSettings: [
				.headerSearchPath("rtc_core_hdrs"),
				.headerSearchPath("include_internal"),
			],
			linkerSettings: [
				.linkedFramework("Network"),
				.linkedFramework("VideoToolbox"),
			]
		),
//		.target(
//			name: "core",
//			dependencies: [
//				.product(name: "libabsl", package: "abseil-cpp"),
//				.product(name: "libjsoncpp", package: "jsoncpp"),
//				.product(name: "libcrypto", package: "boringssl"),
//				.product(name: "libssl", package: "boringssl"),
//				.product(name: "libopus", package: "libopus"),
//				.product(name: "libsrtp", package: "libsrtp"),
//				.product(name: "librnn_vad", package: "rnnoise"),
//				.product(name: "libvpx", package: "libvpx"),
//				.product(name: "libyuv", package: "libyuv"),
//				.product(name: "libcrc32c", package: "crc32c"),
//				.product(name: "libprotobuf-lite", package: "protobuf"),
//			],
//			path: ".",
//			sources: [
//				"net/dcsctp/fuzzers/dcsctp_fuzzers.cc",
//				"net/dcsctp/packet/chunk/abort_chunk.cc",
//				"pc/rtc_stats_traversal.cc",
//				"stats/rtc_stats_report.cc",
//				"net/dcsctp/packet/chunk/chunk.cc",
//				"net/dcsctp/packet/chunk/cookie_ack_chunk.cc",
//				"net/dcsctp/packet/chunk/cookie_echo_chunk.cc",
//				"stats/rtcstats_objects.cc",
//				"net/dcsctp/packet/chunk/data_chunk.cc",
//				"net/dcsctp/packet/chunk/error_chunk.cc",
//				"net/dcsctp/packet/chunk/forward_tsn_chunk.cc",
//				"net/dcsctp/packet/chunk/heartbeat_ack_chunk.cc",
//				"net/dcsctp/packet/chunk/heartbeat_request_chunk.cc",
//				"net/dcsctp/packet/chunk/idata_chunk.cc",
//				"net/dcsctp/packet/chunk/iforward_tsn_chunk.cc",
//				"pc/jsep_transport_collection.cc",
//				"net/dcsctp/packet/chunk/init_ack_chunk.cc",
//				"modules/desktop_capture/screen_drawer_lock_posix.cc",
//				"net/dcsctp/packet/chunk/init_chunk.cc",
//				"net/dcsctp/packet/chunk/reconfig_chunk.cc",
//				"pc/sctp_transport.cc",
//				"net/dcsctp/packet/chunk/sack_chunk.cc",
//				"net/dcsctp/packet/chunk/shutdown_ack_chunk.cc",
//				"net/dcsctp/packet/chunk/shutdown_chunk.cc",
//				"net/dcsctp/packet/chunk/shutdown_complete_chunk.cc",
//				"net/dcsctp/packet/chunk_validators.cc",
//				"net/dcsctp/packet/crc32c.cc",
//				"net/dcsctp/packet/error_cause/cookie_received_while_shutting_down_cause.cc",
//				"net/dcsctp/packet/error_cause/error_cause.cc",
//				"modules/desktop_capture/differ_vector_sse2.cc",
//				"net/dcsctp/packet/error_cause/invalid_mandatory_parameter_cause.cc",
//				"net/dcsctp/packet/error_cause/invalid_stream_identifier_cause.cc",
//				"modules/desktop_capture/mac/desktop_configuration.mm",
//				"net/dcsctp/packet/error_cause/missing_mandatory_parameter_cause.cc",
//				"net/dcsctp/packet/error_cause/no_user_data_cause.cc",
//				"net/dcsctp/packet/error_cause/out_of_resource_error_cause.cc",
//				"net/dcsctp/packet/error_cause/protocol_violation_cause.cc",
//				"net/dcsctp/packet/error_cause/restart_of_an_association_with_new_address_cause.cc",
//				"net/dcsctp/packet/error_cause/stale_cookie_error_cause.cc",
//				"net/dcsctp/packet/error_cause/unrecognized_chunk_type_cause.cc",
//				"net/dcsctp/packet/error_cause/unrecognized_parameter_cause.cc",
//				"net/dcsctp/packet/error_cause/unresolvable_address_cause.cc",
//				"net/dcsctp/packet/error_cause/user_initiated_abort_cause.cc",
//				"net/dcsctp/packet/parameter/add_incoming_streams_request_parameter.cc",
//				"net/dcsctp/packet/parameter/add_outgoing_streams_request_parameter.cc",
//				"net/dcsctp/packet/parameter/forward_tsn_supported_parameter.cc",
//				"net/dcsctp/packet/parameter/heartbeat_info_parameter.cc",
//				"net/dcsctp/packet/parameter/incoming_ssn_reset_request_parameter.cc",
//				"net/dcsctp/packet/parameter/outgoing_ssn_reset_request_parameter.cc",
//				"net/dcsctp/packet/parameter/parameter.cc",
//				"net/dcsctp/packet/parameter/reconfiguration_response_parameter.cc",
//				"net/dcsctp/packet/parameter/ssn_tsn_reset_request_parameter.cc",
//				"net/dcsctp/packet/parameter/state_cookie_parameter.cc",
//				"net/dcsctp/packet/parameter/supported_extensions_parameter.cc",
//				"net/dcsctp/packet/parameter/zero_checksum_acceptable_chunk_parameter.cc",
//				"net/dcsctp/packet/sctp_packet.cc",
//				"pc/peer_connection.cc",
//				"net/dcsctp/packet/tlv_trait.cc",
//				"sdk/objc/components/audio/RTCNativeAudioSessionDelegateAdapter.mm",
//				"net/dcsctp/public/dcsctp_handover_state.cc",
//				"net/dcsctp/public/dcsctp_socket_factory.cc",
//				"net/dcsctp/public/text_pcap_packet_observer.cc",
//				"net/dcsctp/rx/data_tracker.cc",
//				"pc/rtp_parameters_conversion.cc",
//				"net/dcsctp/rx/interleaved_reassembly_streams.cc",
//				"net/dcsctp/rx/reassembly_queue.cc",
//				"net/dcsctp/rx/traditional_reassembly_streams.cc",
//				"net/dcsctp/socket/callback_deferrer.cc",
//				"net/dcsctp/socket/dcsctp_socket.cc",
//				"net/dcsctp/socket/heartbeat_handler.cc",
//				"net/dcsctp/socket/packet_sender.cc",
//				"net/dcsctp/socket/state_cookie.cc",
//				"net/dcsctp/socket/stream_reset_handler.cc",
//				"net/dcsctp/socket/transmission_control_block.cc",
//				"net/dcsctp/timer/task_queue_timeout.cc",
//				"net/dcsctp/timer/timer.cc",
//				"net/dcsctp/tx/outstanding_data.cc",
//				"net/dcsctp/tx/retransmission_error_counter.cc",
//				"net/dcsctp/tx/retransmission_queue.cc",
//				"pc/media_stream_observer.cc",
//				"net/dcsctp/tx/retransmission_timeout.cc",
//				"net/dcsctp/tx/rr_send_queue.cc",
//				"net/dcsctp/tx/stream_scheduler.cc",
//				"p2p/stunprober/stun_prober.cc",
//				"p2p/client/basic_port_allocator.cc",
//				"p2p/client/turn_port_factory.cc",
//				"p2p/base/async_stun_tcp_socket.cc",
//				"p2p/base/basic_async_resolver_factory.cc",
//				"p2p/base/basic_ice_controller.cc",
//				"p2p/base/basic_packet_socket_factory.cc",
//				"pc/webrtc_session_description_factory.cc",
//				"p2p/base/connection_info.cc",
//				"p2p/base/connection.cc",
//				"p2p/base/default_ice_transport_factory.cc",
//				"p2p/base/dtls_transport_internal.cc",
//				"p2p/base/dtls_transport.cc",
//				"p2p/base/ice_controller_interface.cc",
//				"p2p/base/ice_credentials_iterator.cc",
//				"p2p/base/ice_switch_reason.cc",
//				"p2p/base/ice_transport_internal.cc",
//				"pc/ice_server_parsing.cc",
//				"p2p/base/p2p_constants.cc",
//				"p2p/base/p2p_transport_channel.cc",
//				"p2p/base/packet_transport_internal.cc",
//				"p2p/base/port_allocator.cc",
//				"p2p/base/port_interface.cc",
//				"p2p/base/port.cc",
//				"pc/srtp_filter.cc",
//				"p2p/base/pseudo_tcp.cc",
//				"p2p/base/regathering_controller.cc",
//				"p2p/base/stun_port.cc",
//				"p2p/base/stun_request.cc",
//				"p2p/base/stun_server.cc",
//				"pc/transceiver_list.cc",
//				"pc/sdp_utils.cc",
//				"p2p/base/tcp_port.cc",
//				"p2p/base/test_stun_server.cc",
//				"p2p/base/transport_description_factory.cc",
//				"p2p/base/transport_description.cc",
//				"p2p/base/turn_port.cc",
//				"p2p/base/turn_server.cc",
//				"p2p/base/wrapping_active_ice_controller.cc",
//				"logging/rtc_event_log/dependency_descriptor_encoder_decoder.cc",
//				"logging/rtc_event_log/fake_rtc_event_log_factory.cc",
//				"logging/rtc_event_log/fake_rtc_event_log.cc",
//				"logging/rtc_event_log/ice_logger.cc",
//				"logging/rtc_event_log/rtc_event_log_impl.cc",
//				"logging/rtc_event_log/rtc_event_log_parser.cc",
//				"modules/desktop_capture/shared_memory.cc",
//				"logging/rtc_event_log/rtc_event_processor.cc",
//				"logging/rtc_event_log/rtc_stream_config.cc",
//				"logging/rtc_event_log/encoder/bit_writer.cc",
//				"logging/rtc_event_log/encoder/blob_encoding.cc",
//				"logging/rtc_event_log/encoder/delta_encoding.cc",
//				"rtc_base/RTCObjCLogging.mm",
//				"sdk/objc/components/audio/RTCAudioSessionConfiguration.m",
//				"logging/rtc_event_log/encoder/optional_blob_encoding.cc",
//				"logging/rtc_event_log/encoder/rtc_event_log_encoder_common.cc",
//				"logging/rtc_event_log/encoder/rtc_event_log_encoder_legacy.cc",
//				"logging/rtc_event_log/encoder/rtc_event_log_encoder_new_format.cc",
//				"logging/rtc_event_log/encoder/rtc_event_log_encoder_v3.cc",
//				"logging/rtc_event_log/encoder/var_int.cc",
//				"sdk/objc/components/audio/RTCAudioSession.mm",
//				"sdk/objc/native/src/audio/audio_device_module_ios.mm",
//				"logging/rtc_event_log/events/fixed_length_encoding_parameters_v3.cc",
//				"logging/rtc_event_log/events/rtc_event_alr_state.cc",
//				"pc/transport_stats.cc",
//				"logging/rtc_event_log/events/rtc_event_audio_network_adaptation.cc",
//				"logging/rtc_event_log/events/rtc_event_audio_playout.cc",
//				"logging/rtc_event_log/events/rtc_event_audio_receive_stream_config.cc",
//				"logging/rtc_event_log/events/rtc_event_audio_send_stream_config.cc",
//				"logging/rtc_event_log/events/rtc_event_begin_log.cc",
//				"pc/dtmf_sender.cc",
//				"logging/rtc_event_log/events/rtc_event_bwe_update_delay_based.cc",
//				"logging/rtc_event_log/events/rtc_event_bwe_update_loss_based.cc",
//				"logging/rtc_event_log/events/rtc_event_dtls_transport_state.cc",
//				"logging/rtc_event_log/events/rtc_event_dtls_writable_state.cc",
//				"modules/desktop_capture/mac/desktop_frame_cgimage.mm",
//				"logging/rtc_event_log/events/rtc_event_end_log.cc",
//				"logging/rtc_event_log/events/rtc_event_field_encoding_parser.cc",
//				"logging/rtc_event_log/events/rtc_event_field_encoding.cc",
//				"logging/rtc_event_log/events/rtc_event_field_extraction.cc",
//				"logging/rtc_event_log/events/rtc_event_frame_decoded.cc",
//				"logging/rtc_event_log/events/rtc_event_generic_ack_received.cc",
//				"logging/rtc_event_log/events/rtc_event_generic_packet_received.cc",
//				"logging/rtc_event_log/events/rtc_event_generic_packet_sent.cc",
//				"logging/rtc_event_log/events/rtc_event_ice_candidate_pair_config.cc",
//				"logging/rtc_event_log/events/rtc_event_ice_candidate_pair.cc",
//				"logging/rtc_event_log/events/rtc_event_neteq_set_minimum_delay.cc",
//				"logging/rtc_event_log/events/rtc_event_probe_cluster_created.cc",
//				"logging/rtc_event_log/events/rtc_event_probe_result_failure.cc",
//				"logging/rtc_event_log/events/rtc_event_probe_result_success.cc",
//				"logging/rtc_event_log/events/rtc_event_route_change.cc",
//				"logging/rtc_event_log/events/rtc_event_rtcp_packet_incoming.cc",
//				"logging/rtc_event_log/events/rtc_event_rtcp_packet_outgoing.cc",
//				"logging/rtc_event_log/events/rtc_event_rtp_packet_incoming.cc",
//				"logging/rtc_event_log/events/rtc_event_rtp_packet_outgoing.cc",
//				"common_audio/third_party/ooura/fft_size_128/ooura_fft_sse2.cc",
//				"logging/rtc_event_log/events/rtc_event_video_receive_stream_config.cc",
//				"logging/rtc_event_log/events/rtc_event_video_send_stream_config.cc",
//				"modules/desktop_capture/full_screen_application_handler.cc",
//				"video/adaptation/balanced_constraint.cc",
//				"video/adaptation/bandwidth_quality_scaler_resource.cc",
//				"video/adaptation/bitrate_constraint.cc",
//				"video/adaptation/encode_usage_resource.cc",
//				"video/adaptation/overuse_frame_detector.cc",
//				"video/adaptation/pixel_limit_resource.cc",
//				"video/adaptation/quality_rampup_experiment_helper.cc",
//				"video/adaptation/quality_scaler_resource.cc",
//				"video/adaptation/video_stream_encoder_resource_manager.cc",
//				"pc/dtls_srtp_transport.cc",
//				"video/adaptation/video_stream_encoder_resource.cc",
//				"video/alignment_adjuster.cc",
//				"video/buffered_frame_decryptor.cc",
//				"video/call_stats2.cc",
//				"video/config/encoder_stream_factory.cc",
//				"video/config/simulcast.cc",
//				"video/config/video_encoder_config.cc",
//				"video/decode_synchronizer.cc",
//				"video/encoder_bitrate_adjuster.cc",
//				"video/encoder_overshoot_detector.cc",
//				"video/encoder_rtcp_feedback.cc",
//				"video/frame_cadence_adapter.cc",
//				"video/frame_decode_timing.cc",
//				"video/frame_dumping_decoder.cc",
//				"video/frame_encode_metadata_writer.cc",
//				"video/quality_limitation_reason_tracker.cc",
//				"video/receive_statistics_proxy.cc",
//				"video/render/incoming_video_stream.cc",
//				"video/render/video_render_frames.cc",
//				"video/report_block_stats.cc",
//				"pc/proxy.cc",
//				"video/rtp_streams_synchronizer2.cc",
//				"video/rtp_video_stream_receiver2.cc",
//				"video/send_delay_stats.cc",
//				"video/send_statistics_proxy.cc",
//				"pc/rtcp_mux_filter.cc",
//				"video/stats_counter.cc",
//				"modules/desktop_capture/mouse_cursor_monitor_null.cc",
//				"video/stream_synchronization.cc",
//				"video/task_queue_frame_decode_scheduler.cc",
//				"video/transport_adapter.cc",
//				"video/unique_timestamp_counter.cc",
//				"video/video_quality_observer2.cc",
//				"video/video_receive_stream_timeout_tracker.cc",
//				"video/video_receive_stream2.cc",
//				"video/video_send_stream_impl.cc",
//				"video/video_send_stream.cc",
//				"video/video_source_sink_controller.cc",
//				"video/video_stream_buffer_controller.cc",
//				"video/video_stream_decoder2.cc",
//				"video/video_stream_encoder.cc",
//				"audio/audio_level.cc",
//				"audio/audio_receive_stream.cc",
//				"audio/audio_send_stream.cc",
//				"audio/audio_state.cc",
//				"audio/audio_transport_impl.cc",
//				"audio/channel_receive_frame_transformer_delegate.cc",
//				"audio/channel_receive.cc",
//				"audio/channel_send_frame_transformer_delegate.cc",
//				"audio/channel_send.cc",
//				"audio/remix_resample.cc",
//				"audio/utility/channel_mixer.cc",
//				"audio/utility/channel_mixing_matrix.cc",
//				"pc/sdp_offer_answer.cc",
//				"audio/utility/audio_frame_operations.cc",
//				"audio/voip/audio_channel.cc",
//				"stats/rtc_stats.cc",
//				"pc/simulcast_description.cc",
//				"audio/voip/audio_ingress.cc",
//				"audio/voip/voip_core.cc",
//				"modules/desktop_capture/fake_desktop_capturer.cc",
//				"audio/voip/audio_egress.cc",
//				"call/adaptation/adaptation_constraint.cc",
//				"call/adaptation/broadcast_resource_listener.cc",
//				"call/adaptation/degradation_preference_provider.cc",
//				"call/adaptation/encoder_settings.cc",
//				"call/adaptation/resource_adaptation_processor_interface.cc",
//				"call/adaptation/resource_adaptation_processor.cc",
//				"call/adaptation/video_source_restrictions.cc",
//				"call/adaptation/video_stream_adapter.cc",
//				"call/adaptation/video_stream_input_state_provider.cc",
//				"call/adaptation/video_stream_input_state.cc",
//				"call/audio_receive_stream.cc",
//				"call/audio_send_stream.cc",
//				"call/audio_state.cc",
//				"call/bitrate_allocator.cc",
//				"call/call_config.cc",
//				"call/call_factory.cc",
//				"call/call.cc",
//				"call/degraded_call.cc",
//				"call/fake_network_pipe.cc",
//				"call/flexfec_receive_stream_impl.cc",
//				"call/flexfec_receive_stream.cc",
//				"call/receive_time_calculator.cc",
//				"call/rtp_bitrate_configurator.cc",
//				"call/rtp_config.cc",
//				"call/rtp_demuxer.cc",
//				"call/rtp_payload_params.cc",
//				"call/rtp_stream_receiver_controller.cc",
//				"call/rtp_transport_controller_send.cc",
//				"call/rtp_video_sender.cc",
//				"call/rtx_receive_stream.cc",
//				"call/simulated_network.cc",
//				"call/syncable.cc",
//				"call/version.cc",
//				"call/video_receive_stream.cc",
//				"call/video_send_stream.cc",
//				"media/media_constraints.cc",
//				"media/sctp/dcsctp_transport.cc",
//				"media/sctp/sctp_transport_factory.cc",
//				"media/engine/adm_helpers.cc",
//				"pc/rtp_transmission_manager.cc",
//				"media/engine/internal_decoder_factory.cc",
//				"media/engine/internal_encoder_factory.cc",
//				"media/engine/multiplex_codec_factory.cc",
//				"media/engine/payload_type_mapper.cc",
//				"media/engine/simulcast_encoder_adapter.cc",
//				"media/engine/webrtc_media_engine_defaults.cc",
//				"media/engine/webrtc_media_engine.cc",
//				"pc/webrtc_sdp.cc",
//				"media/engine/webrtc_video_engine.cc",
//				"media/engine/webrtc_voice_engine.cc",
//				"media/base/adapted_video_track_source.cc",
//				"media/base/codec.cc",
//				"pc/rtp_transport.cc",
//				"media/base/fake_frame_source.cc",
//				"media/base/fake_media_engine.cc",
//				"media/base/fake_video_renderer.cc",
//				"media/base/media_channel_impl.cc",
//				"media/base/media_constants.cc",
//				"media/base/media_engine.cc",
//				"media/base/rid_description.cc",
//				"media/base/rtp_utils.cc",
//				"media/base/sdp_video_format_utils.cc",
//				"media/base/stream_params.cc",
//				"media/base/test_utils.cc",
//				"media/base/turn_utils.cc",
//				"media/base/video_adapter.cc",
//				"media/base/video_broadcaster.cc",
//				"media/base/video_common.cc",
//				"media/base/video_source_base.cc",
//				"system_wrappers/source/clock.cc",
//				"system_wrappers/source/cpu_features.cc",
//				"system_wrappers/source/cpu_info.cc",
//				"system_wrappers/source/denormal_disabler.cc",
//				"system_wrappers/source/field_trial.cc",
//				"system_wrappers/source/metrics.cc",
//				"system_wrappers/source/rtp_to_ntp_estimator.cc",
//				"system_wrappers/source/sleep.cc",
//				"common_video/bitrate_adjuster.cc",
//				"common_video/frame_rate_estimator.cc",
//				"modules/desktop_capture/desktop_region.cc",
//				"common_video/framerate_controller.cc",
//				"common_video/video_frame_buffer_pool.cc",
//				"common_video/video_frame_buffer.cc",
//				"common_video/generic_frame_descriptor/generic_frame_info.cc",
//				"common_video/h264/h264_bitstream_parser.cc",
//				"common_video/h264/h264_common.cc",
//				"common_video/h264/pps_parser.cc",
//				"common_video/h264/sps_parser.cc",
//				"common_video/h264/sps_vui_rewriter.cc",
//				"common_video/libyuv/webrtc_libyuv.cc",
//				"common_audio/audio_converter.cc",
//				"modules/desktop_capture/desktop_capturer_differ_wrapper.cc",
//				"pc/srtp_transport.cc",
//				"common_audio/audio_util.cc",
//				"modules/desktop_capture/desktop_frame_generator.cc",
//				"common_audio/channel_buffer.cc",
//				"common_audio/fir_filter_avx2.cc",
//				"common_audio/fir_filter_c.cc",
//				"common_audio/fir_filter_factory.cc",
//				"common_audio/fir_filter_neon.cc",
//				"common_audio/real_fourier_ooura.cc",
//				"common_audio/real_fourier.cc",
//				"common_audio/resampler/push_resampler.cc",
//				"common_audio/resampler/push_sinc_resampler.cc",
//				"common_audio/resampler/resampler.cc",
//				"common_audio/resampler/sinc_resampler_avx2.cc",
//				"common_audio/resampler/sinc_resampler_neon.cc",
//				"common_audio/resampler/sinc_resampler.cc",
//				"common_audio/resampler/sinusoidal_linear_chirp_source.cc",
//				"common_audio/ring_buffer.c",
//				"common_audio/signal_processing/auto_corr_to_refl_coef.c",
//				"common_audio/signal_processing/auto_correlation.c",
//				"common_audio/signal_processing/complex_bit_reverse.c",
//				"common_audio/signal_processing/complex_fft.c",
//				"common_audio/signal_processing/copy_set_operations.c",
//				"common_audio/signal_processing/cross_correlation_neon.c",
//				"common_audio/signal_processing/cross_correlation.c",
//				"common_audio/signal_processing/division_operations.c",
//				"common_audio/signal_processing/downsample_fast_neon.c",
//				"common_audio/signal_processing/downsample_fast.c",
//				"common_audio/signal_processing/energy.c",
//				"common_audio/signal_processing/filter_ar_fast_q12.c",
//				"common_audio/signal_processing/filter_ar.c",
//				"common_audio/signal_processing/filter_ma_fast_q12.c",
//				"common_audio/signal_processing/get_hanning_window.c",
//				"common_audio/signal_processing/get_scaling_square.c",
//				"common_audio/signal_processing/ilbc_specific_functions.c",
//				"common_audio/signal_processing/levinson_durbin.c",
//				"common_audio/signal_processing/lpc_to_refl_coef.c",
//				"common_audio/signal_processing/min_max_operations_neon.c",
//				"common_audio/signal_processing/min_max_operations.c",
//				"common_audio/signal_processing/randomization_functions.c",
//				"pc/audio_track.cc",
//				"modules/desktop_capture/differ_block.cc",
//				"generated/modules/audio_coding/audio_network_adaptor/config.pb.cc",
//				"common_audio/signal_processing/real_fft.c",
//				"common_audio/signal_processing/refl_coef_to_lpc.c",
//				"common_audio/signal_processing/resample_48khz.c",
//				"sdk/objc/components/audio/RTCAudioSession+Configuration.mm",
//				"modules/desktop_capture/mac/desktop_frame_iosurface.mm",
//				"common_audio/signal_processing/resample_by_2_internal.c",
//				"common_audio/signal_processing/resample_by_2.c",
//				"common_audio/signal_processing/resample_fractional.c",
//				"common_audio/signal_processing/resample.c",
//				"common_audio/signal_processing/spl_init.c",
//				"common_audio/signal_processing/spl_inl.c",
//				"common_audio/signal_processing/spl_sqrt.c",
//				"modules/desktop_capture/fallback_desktop_capturer_wrapper.cc",
//				"common_audio/signal_processing/splitting_filter.c",
//				"common_audio/signal_processing/sqrt_of_one_minus_x_squared.c",
//				"common_audio/signal_processing/vector_scaling_operations.c",
//				"generated/modules/audio_coding/audio_network_adaptor/debug_dump.pb.cc",
//				"common_audio/signal_processing/dot_product_with_scale.cc",
//				"common_audio/smoothing_filter.cc",
//				"common_audio/third_party/spl_sqrt_floor/spl_sqrt_floor.c",
//				"common_audio/third_party/ooura/fft_size_128/ooura_fft.cc",
//				"common_audio/third_party/ooura/fft_size_128/ooura_fft_neon.cc",
//				"common_audio/third_party/ooura/fft_size_256/fft4g.cc",
//				"common_audio/vad/vad_core.c",
//				"common_audio/vad/vad_filterbank.c",
//				"common_audio/vad/vad_gmm.c",
//				"common_audio/vad/vad_sp.c",
//				"common_audio/vad/webrtc_vad.c",
//				"generated/logging/rtc_event_log/rtc_event_log.pb.cc",
//				"common_audio/vad/vad.cc",
//				"common_audio/wav_file.cc",
//				"common_audio/wav_header.cc",
//				"pc/video_rtp_track_source.cc",
//				"common_audio/window_generator.cc",
//				"pc/jsep_session_description.cc",
//				"modules/audio_device/mac/audio_mixer_manager_mac.mm",
//				"modules/async_audio_processing/async_audio_processing.cc",
//				"modules/audio_coding/codecs/legacy_encoded_audio_frame.cc",
//				"modules/audio_coding/codecs/cng/audio_encoder_cng.cc",
//				"modules/audio_coding/codecs/cng/webrtc_cng.cc",
//				"modules/audio_coding/codecs/g711/g711_interface.c",
//				"modules/audio_coding/codecs/g711/audio_decoder_pcm.cc",
//				"modules/audio_coding/codecs/g711/audio_encoder_pcm.cc",
//				"modules/audio_coding/codecs/g722/g722_interface.c",
//				"modules/audio_coding/codecs/g722/audio_decoder_g722.cc",
//				"modules/audio_coding/codecs/g722/audio_encoder_g722.cc",
//				"modules/audio_coding/codecs/ilbc/abs_quant_loop.c",
//				"modules/audio_coding/codecs/ilbc/abs_quant.c",
//				"modules/audio_coding/codecs/ilbc/augmented_cb_corr.c",
//				"modules/audio_coding/codecs/ilbc/bw_expand.c",
//				"modules/audio_coding/codecs/ilbc/cb_construct.c",
//				"modules/audio_coding/codecs/ilbc/cb_mem_energy_augmentation.c",
//				"modules/audio_coding/codecs/ilbc/cb_mem_energy_calc.c",
//				"modules/audio_coding/codecs/ilbc/cb_mem_energy.c",
//				"modules/audio_coding/codecs/ilbc/cb_search_core.c",
//				"modules/audio_coding/codecs/ilbc/cb_search.c",
//				"modules/audio_coding/codecs/ilbc/cb_update_best_index.c",
//				"modules/audio_coding/codecs/ilbc/chebyshev.c",
//				"modules/audio_coding/codecs/ilbc/comp_corr.c",
//				"modules/audio_coding/codecs/ilbc/constants.c",
//				"modules/audio_coding/codecs/ilbc/create_augmented_vec.c",
//				"modules/audio_coding/codecs/ilbc/decode_residual.c",
//				"modules/audio_coding/codecs/ilbc/decode.c",
//				"modules/audio_coding/codecs/ilbc/decoder_interpolate_lsf.c",
//				"sdk/objc/native/src/audio/audio_device_ios.mm",
//				"modules/audio_coding/codecs/ilbc/do_plc.c",
//				"modules/audio_coding/codecs/ilbc/encode.c",
//				"modules/audio_coding/codecs/ilbc/energy_inverse.c",
//				"modules/audio_coding/codecs/ilbc/enh_upsample.c",
//				"modules/audio_coding/codecs/ilbc/enhancer_interface.c",
//				"modules/audio_coding/codecs/ilbc/enhancer.c",
//				"modules/audio_coding/codecs/ilbc/filtered_cb_vecs.c",
//				"modules/audio_coding/codecs/ilbc/frame_classify.c",
//				"modules/audio_coding/codecs/ilbc/gain_dequant.c",
//				"modules/audio_coding/codecs/ilbc/gain_quant.c",
//				"modules/audio_coding/codecs/ilbc/get_cd_vec.c",
//				"modules/desktop_capture/desktop_capturer_wrapper.cc",
//				"modules/audio_coding/codecs/ilbc/get_lsp_poly.c",
//				"modules/audio_coding/codecs/ilbc/get_sync_seq.c",
//				"modules/audio_coding/codecs/ilbc/hp_input.c",
//				"pc/peer_connection_factory.cc",
//				"modules/audio_coding/codecs/ilbc/hp_output.c",
//				"modules/audio_coding/codecs/ilbc/ilbc.c",
//				"modules/audio_coding/codecs/ilbc/index_conv_dec.c",
//				"modules/audio_coding/codecs/ilbc/index_conv_enc.c",
//				"modules/audio_coding/codecs/ilbc/init_decode.c",
//				"modules/audio_coding/codecs/ilbc/init_encode.c",
//				"modules/audio_coding/codecs/ilbc/interpolate_samples.c",
//				"modules/audio_coding/codecs/ilbc/interpolate.c",
//				"modules/audio_coding/codecs/ilbc/lpc_encode.c",
//				"modules/desktop_capture/rgba_color.cc",
//				"modules/audio_coding/codecs/ilbc/lsf_check.c",
//				"modules/audio_coding/codecs/ilbc/lsf_interpolate_to_poly_dec.c",
//				"modules/audio_coding/codecs/ilbc/lsf_interpolate_to_poly_enc.c",
//				"modules/audio_coding/codecs/ilbc/lsf_to_lsp.c",
//				"modules/audio_coding/codecs/ilbc/lsf_to_poly.c",
//				"pc/sctp_data_channel.cc",
//				"modules/audio_coding/codecs/ilbc/lsp_to_lsf.c",
//				"modules/audio_coding/codecs/ilbc/my_corr.c",
//				"modules/audio_coding/codecs/ilbc/nearest_neighbor.c",
//				"modules/audio_coding/codecs/ilbc/pack_bits.c",
//				"modules/audio_coding/codecs/ilbc/poly_to_lsf.c",
//				"modules/audio_coding/codecs/ilbc/poly_to_lsp.c",
//				"modules/audio_coding/codecs/ilbc/refiner.c",
//				"modules/audio_coding/codecs/ilbc/simple_interpolate_lsf.c",
//				"modules/audio_coding/codecs/ilbc/simple_lpc_analysis.c",
//				"modules/audio_coding/codecs/ilbc/simple_lsf_dequant.c",
//				"modules/audio_coding/codecs/ilbc/simple_lsf_quant.c",
//				"modules/audio_coding/codecs/ilbc/smooth_out_data.c",
//				"modules/audio_coding/codecs/ilbc/smooth.c",
//				"modules/audio_coding/codecs/ilbc/sort_sq.c",
//				"modules/audio_coding/codecs/ilbc/split_vq.c",
//				"pc/media_stream.cc",
//				"modules/audio_coding/codecs/ilbc/state_construct.c",
//				"modules/audio_coding/codecs/ilbc/state_search.c",
//				"modules/audio_coding/codecs/ilbc/swap_bytes.c",
//				"modules/audio_coding/codecs/ilbc/unpack_bits.c",
//				"modules/audio_coding/codecs/ilbc/vq3.c",
//				"modules/audio_coding/codecs/ilbc/vq4.c",
//				"modules/audio_coding/codecs/ilbc/window32_w32.c",
//				"modules/audio_coding/codecs/ilbc/xcorr_coef.c",
//				"modules/audio_coding/codecs/ilbc/audio_decoder_ilbc.cc",
//				"modules/audio_coding/codecs/ilbc/audio_encoder_ilbc.cc",
//				"modules/audio_coding/codecs/isac/main/source/filter_functions.c",
//				"modules/audio_coding/codecs/isac/main/source/isac_vad.c",
//				"pc/srtp_session.cc",
//				"modules/audio_coding/codecs/isac/main/source/pitch_estimator.c",
//				"modules/audio_coding/codecs/isac/main/source/pitch_filter.c",
//				"modules/audio_coding/codecs/opus/audio_coder_opus_common.cc",
//				"pc/legacy_stats_collector.cc",
//				"modules/audio_coding/codecs/opus/audio_decoder_multi_channel_opus_impl.cc",
//				"modules/audio_coding/codecs/opus/audio_decoder_opus.cc",
//				"modules/audio_coding/codecs/opus/audio_encoder_multi_channel_opus_impl.cc",
//				"modules/desktop_capture/mac/full_screen_mac_application_handler.cc",
//				"modules/audio_coding/codecs/opus/audio_encoder_opus.cc",
//				"common_audio/fir_filter_sse.cc",
//				"modules/audio_coding/codecs/opus/opus_interface.cc",
//				"modules/audio_coding/codecs/pcm16b/pcm16b.c",
//				"modules/audio_coding/codecs/pcm16b/audio_decoder_pcm16b.cc",
//				"modules/audio_coding/codecs/pcm16b/audio_encoder_pcm16b.cc",
//				"modules/audio_coding/codecs/pcm16b/pcm16b_common.cc",
//				"modules/audio_coding/codecs/red/audio_encoder_copy_red.cc",
//				"modules/audio_coding/acm2/acm_receiver.cc",
//				"modules/audio_coding/acm2/acm_remixing.cc",
//				"modules/audio_coding/acm2/acm_resampler.cc",
//				"modules/audio_coding/acm2/audio_coding_module.cc",
//				"modules/audio_coding/acm2/call_statistics.cc",
//				"modules/audio_coding/neteq/accelerate.cc",
//				"common_audio/resampler/sinc_resampler_sse.cc",
//				"modules/audio_coding/neteq/audio_multi_vector.cc",
//				"modules/audio_coding/neteq/audio_vector.cc",
//				"modules/audio_coding/neteq/background_noise.cc",
//				"modules/desktop_capture/window_capturer_mac.mm",
//				"modules/audio_coding/neteq/buffer_level_filter.cc",
//				"modules/audio_coding/neteq/comfort_noise.cc",
//				"modules/audio_coding/neteq/cross_correlation.cc",
//				"modules/audio_coding/neteq/decision_logic.cc",
//				"modules/audio_coding/neteq/decoder_database.cc",
//				"modules/audio_coding/neteq/default_neteq_factory.cc",
//				"modules/audio_coding/neteq/delay_manager.cc",
//				"modules/audio_coding/neteq/dsp_helper.cc",
//				"modules/audio_coding/neteq/dtmf_buffer.cc",
//				"modules/audio_coding/neteq/dtmf_tone_generator.cc",
//				"modules/audio_coding/neteq/expand_uma_logger.cc",
//				"modules/desktop_capture/test_utils.cc",
//				"modules/audio_coding/neteq/expand.cc",
//				"modules/desktop_capture/cropped_desktop_frame.cc",
//				"modules/audio_coding/neteq/histogram.cc",
//				"modules/audio_coding/neteq/merge.cc",
//				"modules/audio_coding/neteq/nack_tracker.cc",
//				"modules/audio_coding/neteq/neteq_impl.cc",
//				"modules/audio_coding/neteq/normal.cc",
//				"modules/audio_coding/neteq/packet_arrival_history.cc",
//				"modules/audio_coding/neteq/packet_buffer.cc",
//				"modules/audio_coding/neteq/packet.cc",
//				"modules/audio_coding/neteq/post_decode_vad.cc",
//				"modules/audio_coding/neteq/preemptive_expand.cc",
//				"modules/audio_coding/neteq/random_vector.cc",
//				"modules/audio_coding/neteq/red_payload_splitter.cc",
//				"modules/audio_coding/neteq/reorder_optimizer.cc",
//				"modules/audio_coding/neteq/statistics_calculator.cc",
//				"modules/audio_coding/neteq/sync_buffer.cc",
//				"modules/audio_coding/neteq/time_stretch.cc",
//				"modules/audio_coding/neteq/timestamp_scaler.cc",
//				"modules/audio_coding/neteq/underrun_optimizer.cc",
//				"modules/audio_coding/audio_network_adaptor/audio_network_adaptor_config.cc",
//				"modules/audio_coding/audio_network_adaptor/audio_network_adaptor_impl.cc",
//				"modules/audio_coding/audio_network_adaptor/bitrate_controller.cc",
//				"modules/desktop_capture/shared_desktop_frame.cc",
//				"modules/audio_coding/audio_network_adaptor/channel_controller.cc",
//				"modules/audio_coding/audio_network_adaptor/controller_manager.cc",
//				"modules/audio_coding/audio_network_adaptor/controller.cc",
//				"modules/audio_coding/audio_network_adaptor/debug_dump_writer.cc",
//				"modules/audio_coding/audio_network_adaptor/dtx_controller.cc",
//				"modules/audio_coding/audio_network_adaptor/event_log_writer.cc",
//				"modules/audio_coding/audio_network_adaptor/fec_controller_plr_based.cc",
//				"modules/audio_coding/audio_network_adaptor/frame_length_controller_v2.cc",
//				"modules/audio_coding/audio_network_adaptor/frame_length_controller.cc",
//				"modules/audio_device/audio_device_buffer.cc",
//				"modules/audio_device/audio_device_data_observer.cc",
//				"modules/desktop_capture/desktop_capture_metrics_helper.cc",
//				"modules/audio_device/audio_device_generic.cc",
//				"modules/audio_device/audio_device_impl.cc",
//				"modules/audio_device/audio_device_name.cc",
//				"modules/audio_device/dummy/audio_device_dummy.cc",
//				"modules/audio_device/dummy/file_audio_device_factory.cc",
//				"modules/audio_device/dummy/file_audio_device.cc",
//				"modules/audio_device/fine_audio_buffer.cc",
//				"modules/audio_device/include/audio_device_factory.cc",
//				"modules/audio_mixer/audio_frame_manipulator.cc",
//				"modules/audio_mixer/audio_mixer_impl.cc",
//				"modules/audio_mixer/default_output_rate_calculator.cc",
//				"modules/audio_mixer/frame_combiner.cc",
//				"modules/audio_mixer/gain_change_calculator.cc",
//				"modules/audio_mixer/sine_wave_generator.cc",
//				"modules/audio_processing/audio_buffer.cc",
//				"modules/audio_processing/audio_processing_builder_impl.cc",
//				"modules/audio_processing/audio_processing_impl.cc",
//				"modules/desktop_capture/screen_capturer_null.cc",
//				"modules/audio_processing/echo_control_mobile_impl.cc",
//				"modules/audio_processing/gain_control_impl.cc",
//				"modules/audio_processing/gain_controller2.cc",
//				"modules/audio_processing/high_pass_filter.cc",
//				"modules/audio_processing/optionally_built_submodule_creators.cc",
//				"modules/desktop_capture/mouse_cursor_monitor_mac.mm",
//				"modules/audio_processing/residual_echo_detector.cc",
//				"modules/audio_processing/rms_level.cc",
//				"modules/audio_processing/splitting_filter.cc",
//				"modules/audio_processing/three_band_filter_bank.cc",
//				"modules/audio_processing/aec_dump/aec_dump_impl.cc",
//				"modules/audio_processing/aec_dump/capture_stream_info.cc",
//				"modules/audio_processing/aec_dump/null_aec_dump_factory.cc",
//				"modules/audio_processing/aec3/adaptive_fir_filter_avx2.cc",
//				"modules/audio_processing/aec3/adaptive_fir_filter_erl_avx2.cc",
//				"modules/audio_processing/aec3/adaptive_fir_filter_erl.cc",
//				"modules/audio_processing/aec3/adaptive_fir_filter.cc",
//				"modules/desktop_capture/screen_capturer_helper.cc",
//				"modules/audio_processing/aec3/aec_state.cc",
//				"modules/audio_processing/aec3/aec3_common.cc",
//				"modules/audio_processing/aec3/aec3_fft.cc",
//				"modules/audio_processing/aec3/alignment_mixer.cc",
//				"modules/audio_processing/aec3/api_call_jitter_metrics.cc",
//				"modules/audio_processing/aec3/block_buffer.cc",
//				"modules/audio_processing/aec3/block_delay_buffer.cc",
//				"pc/media_protocol_names.cc",
//				"modules/audio_processing/aec3/block_framer.cc",
//				"modules/audio_processing/aec3/block_processor_metrics.cc",
//				"modules/audio_processing/aec3/block_processor.cc",
//				"modules/audio_processing/aec3/clockdrift_detector.cc",
//				"modules/audio_processing/aec3/coarse_filter_update_gain.cc",
//				"modules/audio_processing/aec3/comfort_noise_generator.cc",
//				"modules/audio_processing/aec3/config_selector.cc",
//				"modules/audio_processing/aec3/decimator.cc",
//				"modules/audio_processing/aec3/dominant_nearend_detector.cc",
//				"modules/audio_processing/aec3/downsampled_render_buffer.cc",
//				"modules/audio_processing/aec3/echo_audibility.cc",
//				"modules/audio_processing/aec3/echo_canceller3.cc",
//				"modules/audio_processing/aec3/echo_path_delay_estimator.cc",
//				"modules/audio_processing/aec3/echo_path_variability.cc",
//				"modules/audio_processing/aec3/echo_remover_metrics.cc",
//				"modules/audio_processing/aec3/echo_remover.cc",
//				"modules/audio_processing/aec3/erl_estimator.cc",
//				"modules/audio_processing/aec3/erle_estimator.cc",
//				"modules/audio_processing/aec3/fft_buffer.cc",
//				"modules/audio_processing/aec3/fft_data_avx2.cc",
//				"modules/audio_processing/aec3/filter_analyzer.cc",
//				"modules/audio_processing/aec3/frame_blocker.cc",
//				"modules/audio_processing/aec3/fullband_erle_estimator.cc",
//				"modules/audio_processing/aec3/matched_filter_avx2.cc",
//				"modules/audio_processing/aec3/matched_filter_lag_aggregator.cc",
//				"modules/audio_processing/aec3/matched_filter.cc",
//				"modules/audio_processing/aec3/moving_average.cc",
//				"modules/audio_processing/aec3/multi_channel_content_detector.cc",
//				"modules/audio_processing/aec3/refined_filter_update_gain.cc",
//				"modules/audio_processing/aec3/render_buffer.cc",
//				"modules/audio_processing/aec3/render_delay_buffer.cc",
//				"modules/audio_processing/aec3/render_delay_controller_metrics.cc",
//				"modules/audio_processing/aec3/render_delay_controller.cc",
//				"modules/audio_processing/aec3/render_signal_analyzer.cc",
//				"modules/audio_processing/aec3/residual_echo_estimator.cc",
//				"modules/audio_processing/aec3/reverb_decay_estimator.cc",
//				"modules/audio_processing/aec3/reverb_frequency_response.cc",
//				"modules/audio_processing/aec3/reverb_model_estimator.cc",
//				"modules/audio_processing/aec3/reverb_model.cc",
//				"modules/audio_processing/aec3/signal_dependent_erle_estimator.cc",
//				"modules/audio_processing/aec3/spectrum_buffer.cc",
//				"modules/audio_processing/aec3/stationarity_estimator.cc",
//				"modules/audio_processing/aec3/subband_erle_estimator.cc",
//				"modules/audio_processing/aec3/subband_nearend_detector.cc",
//				"modules/audio_processing/aec3/subtractor_output_analyzer.cc",
//				"modules/audio_processing/aec3/subtractor_output.cc",
//				"modules/audio_processing/aec3/subtractor.cc",
//				"modules/audio_processing/aec3/suppression_filter.cc",
//				"modules/audio_processing/aec3/suppression_gain.cc",
//				"modules/audio_processing/aec3/transparent_mode.cc",
//				"modules/audio_processing/aec3/vector_math_avx2.cc",
//				"modules/audio_processing/aecm/aecm_core_c.cc",
//				"modules/audio_processing/aecm/aecm_core_neon.cc",
//				"modules/audio_processing/aecm/aecm_core.cc",
//				"modules/audio_processing/aecm/echo_control_mobile.cc",
//				"modules/audio_processing/agc/agc_manager_direct.cc",
//				"modules/audio_processing/agc/agc.cc",
//				"generated/modules/audio_processing/debug.pb.cc",
//				"modules/audio_processing/agc/loudness_histogram.cc",
//				"modules/desktop_capture/mouse_cursor.cc",
//				"modules/audio_processing/agc/utility.cc",
//				"modules/audio_processing/agc/legacy/analog_agc.cc",
//				"modules/audio_processing/agc/legacy/digital_agc.cc",
//				"modules/audio_processing/agc2/adaptive_digital_gain_controller.cc",
//				"modules/audio_processing/agc2/biquad_filter.cc",
//				"modules/audio_processing/agc2/clipping_predictor_level_buffer.cc",
//				"modules/audio_processing/agc2/clipping_predictor.cc",
//				"modules/audio_processing/agc2/compute_interpolated_gain_curve.cc",
//				"modules/audio_processing/agc2/cpu_features.cc",
//				"modules/audio_processing/agc2/fixed_digital_level_estimator.cc",
//				"modules/audio_processing/agc2/gain_applier.cc",
//				"modules/audio_processing/agc2/input_volume_controller.cc",
//				"modules/audio_processing/agc2/input_volume_stats_reporter.cc",
//				"modules/desktop_capture/resolution_tracker.cc",
//				"modules/audio_processing/agc2/interpolated_gain_curve.cc",
//				"modules/audio_processing/agc2/limiter_db_gain_curve.cc",
//				"modules/audio_processing/agc2/limiter.cc",
//				"modules/audio_processing/agc2/noise_level_estimator.cc",
//				"modules/audio_processing/agc2/rnn_vad/auto_correlation.cc",
//				"modules/audio_processing/agc2/rnn_vad/features_extraction.cc",
//				"modules/audio_processing/agc2/rnn_vad/lp_residual.cc",
//				"modules/audio_processing/agc2/rnn_vad/pitch_search_internal.cc",
//				"modules/audio_processing/agc2/rnn_vad/pitch_search.cc",
//				"modules/audio_processing/agc2/rnn_vad/rnn_fc.cc",
//				"modules/audio_processing/agc2/rnn_vad/rnn_gru.cc",
//				"modules/audio_processing/agc2/rnn_vad/rnn_vad_tool.cc",
//				"modules/audio_processing/agc2/rnn_vad/rnn.cc",
//				"modules/audio_processing/agc2/rnn_vad/spectral_features_internal.cc",
//				"modules/desktop_capture/desktop_frame_rotation.cc",
//				"modules/audio_processing/agc2/rnn_vad/spectral_features.cc",
//				"pc/track_media_info_map.cc",
//				"modules/audio_processing/agc2/rnn_vad/vector_math_avx2.cc",
//				"modules/audio_processing/agc2/saturation_protector_buffer.cc",
//				"modules/audio_processing/agc2/saturation_protector.cc",
//				"modules/audio_processing/agc2/speech_level_estimator.cc",
//				"modules/audio_processing/agc2/speech_probability_buffer.cc",
//				"modules/audio_processing/agc2/vad_wrapper.cc",
//				"modules/audio_processing/agc2/vector_float_frame.cc",
//				"modules/audio_processing/capture_levels_adjuster/audio_samples_scaler.cc",
//				"modules/audio_processing/capture_levels_adjuster/capture_levels_adjuster.cc",
//				"modules/audio_processing/echo_detector/circular_buffer.cc",
//				"modules/audio_processing/echo_detector/mean_variance_estimator.cc",
//				"modules/audio_processing/echo_detector/moving_max.cc",
//				"modules/audio_device/mac/audio_device_mac.cc",
//				"pc/session_description.cc",
//				"modules/audio_processing/echo_detector/normalized_covariance_estimator.cc",
//				"modules/audio_processing/include/aec_dump.cc",
//				"modules/audio_processing/include/audio_frame_proxies.cc",
//				"modules/audio_processing/include/audio_processing_statistics.cc",
//				"modules/audio_processing/include/audio_processing.cc",
//				"modules/audio_processing/logging/apm_data_dumper.cc",
//				"modules/audio_processing/ns/fast_math.cc",
//				"modules/audio_processing/ns/histograms.cc",
//				"modules/audio_processing/ns/noise_estimator.cc",
//				"modules/audio_processing/ns/noise_suppressor.cc",
//				"modules/audio_processing/ns/ns_fft.cc",
//				"modules/audio_processing/ns/prior_signal_model_estimator.cc",
//				"modules/audio_processing/ns/prior_signal_model.cc",
//				"modules/audio_processing/ns/quantile_noise_estimator.cc",
//				"modules/audio_processing/ns/signal_model_estimator.cc",
//				"pc/dtls_transport.cc",
//				"modules/audio_processing/ns/signal_model.cc",
//				"modules/audio_processing/ns/speech_probability_estimator.cc",
//				"modules/audio_processing/ns/suppression_params.cc",
//				"modules/audio_processing/ns/wiener_filter.cc",
//				"modules/audio_processing/transient/click_annotate.cc",
//				"modules/audio_processing/transient/file_utils.cc",
//				"modules/audio_processing/transient/moving_moments.cc",
//				"modules/audio_processing/transient/transient_detector.cc",
//				"modules/audio_processing/transient/transient_suppressor_impl.cc",
//				"modules/audio_processing/transient/voice_probability_delay_unit.cc",
//				"modules/audio_processing/transient/wpd_node.cc",
//				"modules/audio_processing/transient/wpd_tree.cc",
//				"modules/audio_processing/utility/cascaded_biquad_filter.cc",
//				"modules/audio_processing/utility/delay_estimator_wrapper.cc",
//				"modules/audio_processing/utility/delay_estimator.cc",
//				"modules/audio_processing/utility/pffft_wrapper.cc",
//				"modules/audio_processing/vad/gmm.cc",
//				"modules/audio_processing/vad/pitch_based_vad.cc",
//				"modules/audio_processing/vad/pitch_internal.cc",
//				"modules/audio_processing/vad/pole_zero_filter.cc",
//				"modules/audio_processing/vad/standalone_vad.cc",
//				"modules/audio_processing/vad/vad_audio_proc.cc",
//				"modules/audio_processing/vad/vad_circular_buffer.cc",
//				"modules/audio_processing/vad/voice_activity_detector.cc",
//				"modules/congestion_controller/receive_side_congestion_controller.cc",
//				"modules/congestion_controller/remb_throttler.cc",
//				"modules/congestion_controller/goog_cc/acknowledged_bitrate_estimator_interface.cc",
//				"pc/rtc_stats_collector.cc",
//				"modules/congestion_controller/goog_cc/acknowledged_bitrate_estimator.cc",
//				"modules/congestion_controller/goog_cc/alr_detector.cc",
//				"generated/logging/rtc_event_log/rtc_event_log2.pb.cc",
//				"modules/congestion_controller/goog_cc/bitrate_estimator.cc",
//				"modules/congestion_controller/goog_cc/congestion_window_pushback_controller.cc",
//				"pc/remote_audio_source.cc",
//				"modules/congestion_controller/goog_cc/delay_based_bwe.cc",
//				"modules/congestion_controller/goog_cc/goog_cc_network_control.cc",
//				"modules/congestion_controller/goog_cc/inter_arrival_delta.cc",
//				"pc/audio_rtp_receiver.cc",
//				"pc/ice_transport.cc",
//				"modules/congestion_controller/goog_cc/link_capacity_estimator.cc",
//				"modules/congestion_controller/goog_cc/loss_based_bandwidth_estimation.cc",
//				"modules/congestion_controller/goog_cc/loss_based_bwe_v2.cc",
//				"modules/congestion_controller/goog_cc/probe_bitrate_estimator.cc",
//				"modules/congestion_controller/goog_cc/probe_controller.cc",
//				"modules/congestion_controller/goog_cc/robust_throughput_estimator.cc",
//				"modules/congestion_controller/goog_cc/send_side_bandwidth_estimation.cc",
//				"pc/sctp_utils.cc",
//				"modules/congestion_controller/goog_cc/trendline_estimator.cc",
//				"modules/congestion_controller/pcc/bitrate_controller.cc",
//				"modules/congestion_controller/pcc/monitor_interval.cc",
//				"modules/congestion_controller/pcc/pcc_factory.cc",
//				"modules/desktop_capture/blank_detector_desktop_capturer_wrapper.cc",
//				"modules/congestion_controller/pcc/pcc_network_controller.cc",
//				"modules/congestion_controller/pcc/rtt_tracker.cc",
//				"modules/congestion_controller/pcc/utility_function.cc",
//				"modules/desktop_capture/desktop_capture_options.cc",
//				"modules/congestion_controller/rtp/control_handler.cc",
//				"modules/congestion_controller/rtp/transport_feedback_adapter.cc",
//				"modules/congestion_controller/rtp/transport_feedback_demuxer.cc",
//				"modules/pacing/bitrate_prober.cc",
//				"modules/pacing/interval_budget.cc",
//				"modules/pacing/pacing_controller.cc",
//				"modules/pacing/packet_router.cc",
//				"modules/pacing/prioritized_packet_queue.cc",
//				"modules/pacing/task_queue_paced_sender.cc",
//				"modules/remote_bitrate_estimator/aimd_rate_control.cc",
//				"modules/remote_bitrate_estimator/bwe_defines.cc",
//				"modules/remote_bitrate_estimator/inter_arrival.cc",
//				"modules/remote_bitrate_estimator/overuse_detector.cc",
//				"pc/usage_pattern.cc",
//				"modules/remote_bitrate_estimator/overuse_estimator.cc",
//				"modules/remote_bitrate_estimator/packet_arrival_map.cc",
//				"modules/remote_bitrate_estimator/remote_bitrate_estimator_abs_send_time.cc",
//				"modules/remote_bitrate_estimator/remote_bitrate_estimator_single_stream.cc",
//				"modules/remote_bitrate_estimator/remote_estimator_proxy.cc",
//				"modules/desktop_capture/window_finder_mac.mm",
//				"modules/rtp_rtcp/include/report_block_data.cc",
//				"modules/rtp_rtcp/include/rtp_rtcp_defines.cc",
//				"modules/rtp_rtcp/source/absolute_capture_time_interpolator.cc",
//				"modules/rtp_rtcp/source/absolute_capture_time_sender.cc",
//				"modules/rtp_rtcp/source/active_decode_targets_helper.cc",
//				"modules/rtp_rtcp/source/capture_clock_offset_updater.cc",
//				"modules/rtp_rtcp/source/create_video_rtp_depacketizer.cc",
//				"modules/rtp_rtcp/source/deprecated/deprecated_rtp_sender_egress.cc",
//				"modules/rtp_rtcp/source/dtmf_queue.cc",
//				"modules/rtp_rtcp/source/fec_private_tables_bursty.cc",
//				"modules/rtp_rtcp/source/fec_private_tables_random.cc",
//				"modules/rtp_rtcp/source/flexfec_03_header_reader_writer.cc",
//				"modules/rtp_rtcp/source/flexfec_header_reader_writer.cc",
//				"modules/rtp_rtcp/source/flexfec_receiver.cc",
//				"modules/rtp_rtcp/source/flexfec_sender.cc",
//				"modules/rtp_rtcp/source/forward_error_correction_internal.cc",
//				"modules/rtp_rtcp/source/forward_error_correction.cc",
//				"modules/rtp_rtcp/source/frame_object.cc",
//				"modules/rtp_rtcp/source/leb128.cc",
//				"modules/desktop_capture/mac/desktop_configuration_monitor.cc",
//				"modules/rtp_rtcp/source/packet_loss_stats.cc",
//				"modules/rtp_rtcp/source/packet_sequencer.cc",
//				"modules/rtp_rtcp/source/receive_statistics_impl.cc",
//				"modules/rtp_rtcp/source/remote_ntp_time_estimator.cc",
//				"modules/rtp_rtcp/source/rtcp_nack_stats.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/app.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/bye.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/common_header.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/compound_packet.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/dlrr.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/extended_reports.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/fir.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/loss_notification.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/nack.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/pli.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/psfb.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/rapid_resync_request.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/receiver_report.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/remb.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/remote_estimate.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/report_block.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/rrtr.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/rtpfb.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/sdes.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/sender_report.cc",
//				"modules/desktop_capture/mac/screen_capturer_mac.mm",
//				"modules/rtp_rtcp/source/rtcp_packet/target_bitrate.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/tmmb_item.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/tmmbn.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/tmmbr.cc",
//				"modules/rtp_rtcp/source/rtcp_packet/transport_feedback.cc",
//				"modules/rtp_rtcp/source/rtcp_packet.cc",
//				"modules/rtp_rtcp/source/rtcp_receiver.cc",
//				"modules/rtp_rtcp/source/rtcp_sender.cc",
//				"modules/rtp_rtcp/source/rtcp_transceiver_config.cc",
//				"modules/rtp_rtcp/source/rtcp_transceiver_impl.cc",
//				"modules/rtp_rtcp/source/rtcp_transceiver.cc",
//				"modules/rtp_rtcp/source/rtp_dependency_descriptor_extension.cc",
//				"modules/rtp_rtcp/source/rtp_dependency_descriptor_reader.cc",
//				"modules/rtp_rtcp/source/rtp_dependency_descriptor_writer.cc",
//				"modules/rtp_rtcp/source/rtp_descriptor_authentication.cc",
//				"modules/rtp_rtcp/source/rtp_format_h264.cc",
//				"modules/rtp_rtcp/source/rtp_format_video_generic.cc",
//				"modules/rtp_rtcp/source/rtp_format_vp8.cc",
//				"modules/rtp_rtcp/source/rtp_format_vp9.cc",
//				"modules/rtp_rtcp/source/rtp_format.cc",
//				"sdk/objc/native/src/audio/voice_processing_audio_unit.mm",
//				"modules/rtp_rtcp/source/rtp_generic_frame_descriptor_extension.cc",
//				"modules/rtp_rtcp/source/rtp_generic_frame_descriptor.cc",
//				"modules/rtp_rtcp/source/rtp_header_extension_map.cc",
//				"modules/rtp_rtcp/source/rtp_header_extension_size.cc",
//				"modules/rtp_rtcp/source/rtp_header_extensions.cc",
//				"modules/rtp_rtcp/source/rtp_packet_history.cc",
//				"modules/rtp_rtcp/source/rtp_packet_received.cc",
//				"modules/rtp_rtcp/source/rtp_packet_to_send.cc",
//				"modules/rtp_rtcp/source/rtp_packet.cc",
//				"modules/rtp_rtcp/source/rtp_packetizer_av1.cc",
//				"modules/rtp_rtcp/source/rtp_rtcp_impl.cc",
//				"modules/rtp_rtcp/source/rtp_rtcp_impl2.cc",
//				"modules/rtp_rtcp/source/rtp_sender_audio.cc",
//				"modules/rtp_rtcp/source/rtp_sender_egress.cc",
//				"modules/rtp_rtcp/source/rtp_sender_video_frame_transformer_delegate.cc",
//				"modules/rtp_rtcp/source/rtp_sender_video.cc",
//				"modules/rtp_rtcp/source/rtp_sender.cc",
//				"modules/rtp_rtcp/source/rtp_sequence_number_map.cc",
//				"modules/rtp_rtcp/source/rtp_util.cc",
//				"modules/rtp_rtcp/source/rtp_video_header.cc",
//				"modules/rtp_rtcp/source/rtp_video_layers_allocation_extension.cc",
//				"modules/rtp_rtcp/source/rtp_video_stream_receiver_frame_transformer_delegate.cc",
//				"modules/rtp_rtcp/source/source_tracker.cc",
//				"modules/rtp_rtcp/source/time_util.cc",
//				"modules/rtp_rtcp/source/tmmbr_help.cc",
//				"modules/rtp_rtcp/source/ulpfec_generator.cc",
//				"modules/rtp_rtcp/source/ulpfec_header_reader_writer.cc",
//				"modules/rtp_rtcp/source/ulpfec_receiver.cc",
//				"pc/video_rtp_receiver.cc",
//				"modules/rtp_rtcp/source/video_rtp_depacketizer_av1.cc",
//				"modules/desktop_capture/desktop_and_cursor_composer.cc",
//				"modules/rtp_rtcp/source/video_rtp_depacketizer_generic.cc",
//				"modules/rtp_rtcp/source/video_rtp_depacketizer_h264.cc",
//				"modules/rtp_rtcp/source/video_rtp_depacketizer_raw.cc",
//				"modules/rtp_rtcp/source/video_rtp_depacketizer_vp8.cc",
//				"pc/video_track_source.cc",
//				"modules/rtp_rtcp/source/video_rtp_depacketizer_vp9.cc",
//				"modules/rtp_rtcp/source/video_rtp_depacketizer.cc",
//				"modules/third_party/g711/g711.c",
//				"modules/third_party/g722/g722_decode.c",
//				"modules/third_party/g722/g722_encode.c",
//				"modules/third_party/fft/fft.c",
//				"modules/third_party/portaudio/pa_ringbuffer.c",
//				"modules/video_capture/device_info_impl.cc",
//				"modules/video_capture/video_capture_factory_null.cc",
//				"modules/video_capture/video_capture_factory.cc",
//				"modules/video_capture/video_capture_impl.cc",
//				"modules/video_capture/video_capture_options.cc",
//				"modules/video_coding/chain_diff_calculator.cc",
//				"modules/video_coding/codecs/av1/av1_svc_config.cc",
//				"modules/video_coding/codecs/av1/dav1d_decoder.cc",
//				"modules/video_coding/codecs/av1/libaom_av1_encoder.cc",
//				"modules/video_coding/codecs/h264/h264_encoder_impl.cc",
//				"modules/video_coding/codecs/h264/h264.cc",
//				"modules/video_coding/codecs/h264/h264_decoder_impl.cc",
//				"modules/video_coding/codecs/h264/h264_color_space.cc",
//				"modules/video_coding/codecs/interface/libvpx_interface.cc",
//				"modules/video_coding/codecs/multiplex/multiplex_encoded_image_packer.cc",
//				"modules/video_coding/codecs/multiplex/multiplex_decoder_adapter.cc",
//				"modules/video_coding/codecs/multiplex/augmented_video_frame_buffer.cc",
//				"modules/video_coding/codecs/multiplex/multiplex_encoder_adapter.cc",
//				"modules/video_coding/codecs/vp8/default_temporal_layers.cc",
//				"modules/video_coding/codecs/vp8/libvpx_vp8_decoder.cc",
//				"modules/video_coding/codecs/vp8/libvpx_vp8_encoder.cc",
//				"modules/video_coding/codecs/vp8/screenshare_layers.cc",
//				"modules/video_coding/codecs/vp8/temporal_layers_checker.cc",
//				"pc/peer_connection_message_handler.cc",
//				"modules/video_coding/codecs/vp8/vp8_scalability.cc",
//				"pc/connection_context.cc",
//				"modules/video_coding/codecs/vp9/libvpx_vp9_decoder.cc",
//				"modules/video_coding/codecs/vp9/libvpx_vp9_encoder.cc",
//				"modules/video_coding/codecs/vp9/svc_config.cc",
//				"modules/video_coding/codecs/vp9/vp9_frame_buffer_pool.cc",
//				"modules/video_coding/codecs/vp9/vp9.cc",
//				"pc/data_channel_controller.cc",
//				"modules/video_coding/decoder_database.cc",
//				"modules/video_coding/deprecated/decoding_state.cc",
//				"modules/video_coding/deprecated/event_wrapper.cc",
//				"modules/desktop_capture/window_capturer_null.cc",
//				"modules/video_coding/deprecated/frame_buffer.cc",
//				"pc/rtp_media_utils.cc",
//				"modules/video_coding/deprecated/jitter_buffer.cc",
//				"modules/video_coding/deprecated/packet.cc",
//				"modules/video_coding/deprecated/receiver.cc",
//				"modules/video_coding/deprecated/session_info.cc",
//				"modules/video_coding/deprecated/stream_generator.cc",
//				"modules/video_coding/encoded_frame.cc",
//				"modules/video_coding/fec_controller_default.cc",
//				"modules/video_coding/frame_dependencies_calculator.cc",
//				"pc/jsep_transport_controller.cc",
//				"modules/video_coding/frame_helpers.cc",
//				"pc/data_channel_utils.cc",
//				"modules/video_coding/generic_decoder.cc",
//				"modules/video_coding/h264_packet_buffer.cc",
//				"modules/video_coding/h264_sprop_parameter_sets.cc",
//				"modules/video_coding/h264_sps_pps_tracker.cc",
//				"modules/video_coding/histogram.cc",
//				"modules/video_coding/include/video_codec_interface.cc",
//				"modules/video_coding/loss_notification_controller.cc",
//				"modules/video_coding/media_opt_util.cc",
//				"modules/video_coding/nack_requester.cc",
//				"modules/video_coding/packet_buffer.cc",
//				"modules/video_coding/rtp_frame_id_only_ref_finder.cc",
//				"modules/video_coding/rtp_frame_reference_finder.cc",
//				"modules/video_coding/rtp_generic_ref_finder.cc",
//				"modules/video_coding/rtp_seq_num_only_ref_finder.cc",
//				"modules/video_coding/rtp_vp8_ref_finder.cc",
//				"modules/video_coding/rtp_vp9_ref_finder.cc",
//				"modules/video_coding/svc/create_scalability_structure.cc",
//				"modules/video_coding/svc/scalability_mode_util.cc",
//				"modules/video_coding/svc/scalability_structure_full_svc.cc",
//				"modules/video_coding/svc/scalability_structure_key_svc.cc",
//				"modules/video_coding/svc/scalability_structure_l2t2_key_shift.cc",
//				"modules/video_coding/svc/scalability_structure_simulcast.cc",
//				"modules/video_coding/svc/scalable_video_controller_no_layering.cc",
//				"modules/video_coding/svc/svc_rate_allocator.cc",
//				"modules/video_coding/timing/decode_time_percentile_filter.cc",
//				"modules/video_coding/timing/frame_delay_variation_kalman_filter.cc",
//				"modules/video_coding/timing/inter_frame_delay_variation_calculator.cc",
//				"modules/video_coding/timing/jitter_estimator.cc",
//				"modules/video_coding/timing/rtt_filter.cc",
//				"modules/video_coding/timing/timestamp_extrapolator.cc",
//				"modules/video_coding/timing/timing.cc",
//				"modules/video_coding/utility/bandwidth_quality_scaler.cc",
//				"modules/video_coding/utility/decoded_frames_history.cc",
//				"modules/video_coding/utility/frame_dropper.cc",
//				"modules/video_coding/utility/framerate_controller_deprecated.cc",
//				"modules/video_coding/utility/ivf_file_reader.cc",
//				"modules/video_coding/utility/ivf_file_writer.cc",
//				"modules/video_coding/utility/qp_parser.cc",
//				"pc/sdp_serializer.cc",
//				"modules/video_coding/utility/quality_scaler.cc",
//				"modules/video_coding/utility/simulcast_rate_allocator.cc",
//				"modules/video_coding/utility/simulcast_utility.cc",
//				"modules/video_coding/utility/vp8_header_parser.cc",
//				"modules/video_coding/utility/vp9_uncompressed_header_parser.cc",
//				"modules/video_coding/video_codec_initializer.cc",
//				"modules/video_coding/video_coding_defines.cc",
//				"modules/video_coding/video_coding_impl.cc",
//				"modules/video_coding/video_receiver.cc",
//				"modules/video_coding/video_receiver2.cc",
//				"api/adaptation/resource.cc",
//				"api/audio/audio_frame.cc",
//				"api/audio/echo_detector_creator.cc",
//				"api/audio/echo_canceller3_config_json.cc",
//				"api/audio/echo_canceller3_config.cc",
//				"api/audio/channel_layout.cc",
//				"api/audio/echo_canceller3_factory.cc",
//				"api/audio_codecs/L16/audio_decoder_L16.cc",
//				"api/audio_codecs/L16/audio_encoder_L16.cc",
//				"pc/jsep_ice_candidate.cc",
//				"api/audio_codecs/g711/audio_decoder_g711.cc",
//				"api/audio_codecs/g711/audio_encoder_g711.cc",
//				"api/audio_codecs/opus_audio_encoder_factory.cc",
//				"api/audio_codecs/audio_encoder.cc",
//				"api/audio_codecs/opus/audio_encoder_multi_channel_opus_config.cc",
//				"api/audio_codecs/opus/audio_encoder_opus_config.cc",
//				"api/audio_codecs/opus/audio_encoder_opus.cc",
//				"api/audio_codecs/opus/audio_encoder_multi_channel_opus.cc",
//				"api/audio_codecs/opus/audio_decoder_opus.cc",
//				"api/audio_codecs/opus/audio_decoder_multi_channel_opus.cc",
//				"api/audio_codecs/builtin_audio_decoder_factory.cc",
//				"api/audio_codecs/audio_decoder.cc",
//				"api/audio_codecs/g722/audio_encoder_g722.cc",
//				"api/audio_codecs/g722/audio_decoder_g722.cc",
//				"api/audio_codecs/audio_format.cc",
//				"api/audio_codecs/builtin_audio_encoder_factory.cc",
//				"api/audio_codecs/audio_codec_pair_id.cc",
//				"api/audio_codecs/opus_audio_decoder_factory.cc",
//				"api/audio_codecs/ilbc/audio_encoder_ilbc.cc",
//				"api/audio_codecs/ilbc/audio_decoder_ilbc.cc",
//				"api/audio_options.cc",
//				"api/call/transport.cc",
//				"api/candidate.cc",
//				"api/create_peerconnection_factory.cc",
//				"api/crypto/crypto_options.cc",
//				"api/data_channel_interface.cc",
//				"api/dtls_transport_interface.cc",
//				"api/field_trials_registry.cc",
//				"api/field_trials.cc",
//				"api/frame_transformer_factory.cc",
//				"pc/external_hmac.cc",
//				"api/ice_transport_factory.cc",
//				"api/jsep_ice_candidate.cc",
//				"api/jsep.cc",
//				"api/legacy_stats_types.cc",
//				"api/media_stream_interface.cc",
//				"api/media_types.cc",
//				"api/neteq/custom_neteq_factory.cc",
//				"api/neteq/default_neteq_controller_factory.cc",
//				"api/neteq/tick_timer.cc",
//				"api/neteq/neteq.cc",
//				"api/numerics/samples_stats_counter.cc",
//				"api/peer_connection_interface.cc",
//				"api/rtc_error.cc",
//				"api/rtc_event_log/rtc_event.cc",
//				"api/rtc_event_log/rtc_event_log.cc",
//				"api/rtc_event_log/rtc_event_log_factory.cc",
//				"api/rtc_event_log_output_file.cc",
//				"pc/video_track.cc",
//				"api/rtp_headers.cc",
//				"api/rtp_packet_info.cc",
//				"api/rtp_parameters.cc",
//				"api/rtp_receiver_interface.cc",
//				"api/rtp_sender_interface.cc",
//				"pc/rtp_sender.cc",
//				"api/rtp_transceiver_interface.cc",
//				"api/sctp_transport_interface.cc",
//				"api/task_queue/default_task_queue_factory_gcd.cc",
//				"api/task_queue/default_task_queue_factory_libevent.cc",
//				"api/task_queue/task_queue_base.cc",
//				"api/task_queue/default_task_queue_factory_stdlib_or_libevent_experiment.cc",
//				"api/task_queue/default_task_queue_factory_stdlib.cc",
//				"api/task_queue/pending_task_safety_flag.cc",
//				"api/transport/bitrate_settings.cc",
//				"api/transport/field_trial_based_config.cc",
//				"api/transport/rtp/dependency_descriptor.cc",
//				"api/transport/stun.cc",
//				"api/transport/network_types.cc",
//				"api/transport/goog_cc_factory.cc",
//				"api/units/timestamp.cc",
//				"api/units/time_delta.cc",
//				"api/units/data_rate.cc",
//				"api/units/data_size.cc",
//				"api/units/frequency.cc",
//				"api/video/i210_buffer.cc",
//				"api/video/video_adaptation_counters.cc",
//				"api/video/i422_buffer.cc",
//				"api/video/video_frame_metadata.cc",
//				"api/video/encoded_frame.cc",
//				"pc/media_session.cc",
//				"api/video/i410_buffer.cc",
//				"modules/desktop_capture/mac/desktop_frame_provider.mm",
//				"api/video/video_bitrate_allocation.cc",
//				"modules/desktop_capture/mac/window_list_utils.cc",
//				"pc/rtp_receiver.cc",
//				"modules/desktop_capture/desktop_frame.cc",
//				"api/video/color_space.cc",
//				"api/video/builtin_video_bitrate_allocator_factory.cc",
//				"api/video/encoded_image.cc",
//				"api/video/hdr_metadata.cc",
//				"api/video/frame_buffer.cc",
//				"modules/desktop_capture/screen_drawer_mac.cc",
//				"modules/desktop_capture/desktop_capturer.cc",
//				"api/video/i420_buffer.cc",
//				"api/video/video_content_type.cc",
//				"api/video/rtp_video_frame_assembler.cc",
//				"api/video/video_frame.cc",
//				"api/video/video_bitrate_allocator.cc",
//				"api/video/i010_buffer.cc",
//				"api/video/i444_buffer.cc",
//				"api/video/video_timing.cc",
//				"api/video/video_frame_buffer.cc",
//				"api/video/video_source_interface.cc",
//				"api/video/nv12_buffer.cc",
//				"api/video_codecs/av1_profile.cc",
//				"pc/jsep_transport.cc",
//				"api/video_codecs/builtin_video_decoder_factory.cc",
//				"api/video_codecs/builtin_video_encoder_factory.cc",
//				"api/video_codecs/h264_profile_level_id.cc",
//				"api/video_codecs/scalability_mode_helper.cc",
//				"api/video_codecs/scalability_mode.cc",
//				"api/video_codecs/sdp_video_format.cc",
//				"api/video_codecs/simulcast_stream.cc",
//				"api/video_codecs/spatial_layer.cc",
//				"api/video_codecs/video_codec.cc",
//				"api/video_codecs/video_decoder_software_fallback_wrapper.cc",
//				"api/video_codecs/video_decoder.cc",
//				"api/video_codecs/video_encoder_software_fallback_wrapper.cc",
//				"modules/desktop_capture/screen_drawer.cc",
//				"api/video_codecs/video_encoder.cc",
//				"api/video_codecs/vp8_frame_config.cc",
//				"api/video_codecs/vp8_temporal_layers_factory.cc",
//				"api/video_codecs/vp8_temporal_layers.cc",
//				"api/video_codecs/vp9_profile.cc",
//				"api/voip/voip_engine_factory.cc",
//				"api/wrapping_async_dns_resolver.cc",
//				"rtc_base/async_packet_socket.cc",
//				"rtc_base/async_resolver_interface.cc",
//				"rtc_base/async_resolver.cc",
//				"rtc_base/async_socket.cc",
//				"rtc_base/async_tcp_socket.cc",
//				"rtc_base/async_udp_socket.cc",
//				"rtc_base/bit_buffer.cc",
//				"rtc_base/bitstream_reader.cc",
//				"rtc_base/boringssl_certificate.cc",
//				"rtc_base/boringssl_identity.cc",
//				"rtc_base/buffer_queue.cc",
//				"rtc_base/byte_buffer.cc",
//				"rtc_base/callback_list.cc",
//				"rtc_base/checks.cc",
//				"rtc_base/containers/flat_tree.cc",
//				"rtc_base/copy_on_write_buffer.cc",
//				"modules/desktop_capture/screen_capturer_darwin.mm",
//				"rtc_base/cpu_time.cc",
//				"rtc_base/crc32.cc",
//				"rtc_base/crypt_string.cc",
//				"modules/desktop_capture/window_finder.cc",
//				"rtc_base/data_rate_limiter.cc",
//				"rtc_base/deprecated/recursive_critical_section.cc",
//				"rtc_base/event_tracer.cc",
//				"rtc_base/event.cc",
//				"rtc_base/experiments/alr_experiment.cc",
//				"rtc_base/experiments/balanced_degradation_settings.cc",
//				"rtc_base/experiments/bandwidth_quality_scaler_settings.cc",
//				"rtc_base/experiments/cpu_speed_experiment.cc",
//				"rtc_base/experiments/encoder_info_settings.cc",
//				"rtc_base/experiments/field_trial_list.cc",
//				"rtc_base/experiments/field_trial_parser.cc",
//				"rtc_base/experiments/field_trial_units.cc",
//				"rtc_base/experiments/keyframe_interval_settings.cc",
//				"rtc_base/experiments/min_video_bitrate_experiment.cc",
//				"rtc_base/experiments/normalize_simulcast_size_experiment.cc",
//				"rtc_base/experiments/quality_rampup_experiment.cc",
//				"rtc_base/experiments/quality_scaler_settings.cc",
//				"rtc_base/experiments/quality_scaling_experiment.cc",
//				"rtc_base/experiments/rate_control_settings.cc",
//				"rtc_base/experiments/rtt_mult_experiment.cc",
//				"rtc_base/experiments/stable_target_rate_experiment.cc",
//				"rtc_base/experiments/struct_parameters_parser.cc",
//				"rtc_base/fake_clock.cc",
//				"rtc_base/fake_ssl_identity.cc",
//				"rtc_base/file_rotating_stream.cc",
//				"rtc_base/firewall_socket_server.cc",
//				"rtc_base/helpers.cc",
//				"rtc_base/http_common.cc",
//				"rtc_base/ifaddrs_android.cc",
//				"rtc_base/ifaddrs_converter.cc",
//				"rtc_base/internal/default_socket_server.cc",
//				"rtc_base/ip_address.cc",
//				"rtc_base/log_sinks.cc",
//				"rtc_base/logging.cc",
//				"rtc_base/mac_ifaddrs_converter.cc",
//				"rtc_base/memory/aligned_malloc.cc",
//				"rtc_base/memory/fifo_buffer.cc",
//				"rtc_base/memory_stream.cc",
//				"rtc_base/memory_usage.cc",
//				"rtc_base/message_digest.cc",
//				"rtc_base/nat_server.cc",
//				"rtc_base/nat_socket_factory.cc",
//				"rtc_base/nat_types.cc",
//				"rtc_base/net_helper.cc",
//				"modules/desktop_capture/full_screen_window_detector.cc",
//				"pc/local_audio_source.cc",
//				"rtc_base/net_helpers.cc",
//				"rtc_base/network/sent_packet.cc",
//				"rtc_base/network_constants.cc",
//				"rtc_base/network_monitor_factory.cc",
//				"rtc_base/network_monitor.cc",
//				"rtc_base/network_route.cc",
//				"rtc_base/network.cc",
//				"modules/desktop_capture/desktop_geometry.cc",
//				"rtc_base/null_socket_server.cc",
//				"rtc_base/numerics/exp_filter.cc",
//				"rtc_base/numerics/event_based_exponential_moving_average.cc",
//				"rtc_base/numerics/sample_stats.cc",
//				"rtc_base/numerics/moving_average.cc",
//				"rtc_base/numerics/histogram_percentile_counter.cc",
//				"rtc_base/numerics/sample_counter.cc",
//				"rtc_base/numerics/event_rate_counter.cc",
//				"pc/video_track_source_proxy.cc",
//				"rtc_base/openssl_adapter.cc",
//				"modules/desktop_capture/cropping_window_capturer.cc",
//				"rtc_base/openssl_certificate.cc",
//				"rtc_base/openssl_digest.cc",
//				"rtc_base/openssl_identity.cc",
//				"sdk/objc/native/src/audio/audio_helpers.mm",
//				"rtc_base/openssl_key_pair.cc",
//				"rtc_base/openssl_session_cache.cc",
//				"rtc_base/openssl_stream_adapter.cc",
//				"rtc_base/openssl_utility.cc",
//				"rtc_base/operations_chain.cc",
//				"pc/rtp_transceiver.cc",
//				"rtc_base/physical_socket_server.cc",
//				"rtc_base/system/cocoa_threading.mm",
//				"rtc_base/platform_thread_types.cc",
//				"rtc_base/platform_thread.cc",
//				"rtc_base/proxy_info.cc",
//				"rtc_base/proxy_server.cc",
//				"rtc_base/race_checker.cc",
//				"rtc_base/random.cc",
//				"rtc_base/rate_limiter.cc",
//				"rtc_base/rate_statistics.cc",
//				"rtc_base/rate_tracker.cc",
//				"rtc_base/rtc_certificate_generator.cc",
//				"rtc_base/rtc_certificate.cc",
//				"rtc_base/server_socket_adapters.cc",
//				"rtc_base/socket_adapters.cc",
//				"rtc_base/socket_address_pair.cc",
//				"rtc_base/socket_address.cc",
//				"rtc_base/socket_stream.cc",
//				"rtc_base/socket.cc",
//				"rtc_base/ssl_adapter.cc",
//				"rtc_base/ssl_certificate.cc",
//				"rtc_base/ssl_fingerprint.cc",
//				"rtc_base/ssl_identity.cc",
//				"rtc_base/system/gcd_helpers.m",
//				"rtc_base/ssl_stream_adapter.cc",
//				"rtc_base/stream.cc",
//				"rtc_base/string_encode.cc",
//				"rtc_base/string_to_number.cc",
//				"rtc_base/string_utils.cc",
//				"rtc_base/strings/json.cc",
//				"rtc_base/strings/string_format.cc",
//				"rtc_base/strings/string_builder.cc",
//				"rtc_base/strings/audio_format_to_string.cc",
//				"rtc_base/synchronization/yield.cc",
//				"rtc_base/synchronization/yield_policy.cc",
//				"rtc_base/synchronization/sequence_checker_internal.cc",
//				"rtc_base/system/file_wrapper.cc",
//				"rtc_base/system/warn_current_thread_is_deadlocked.cc",
//				"rtc_base/system_time.cc",
//				"rtc_base/task_queue_gcd.cc",
//				"rtc_base/task_queue_libevent.cc",
//				"pc/channel.cc",
//				"rtc_base/task_queue_stdlib.cc",
//				"rtc_base/task_queue.cc",
//				"rtc_base/task_utils/repeating_task.cc",
//				"rtc_base/third_party/sigslot/sigslot.cc",
//				"pc/jitter_buffer_delay.cc",
//				"rtc_base/third_party/base64/base64.cc",
//				"rtc_base/thread.cc",
//				"rtc_base/time_utils.cc",
//				"rtc_base/timestamp_aligner.cc",
//				"rtc_base/unique_id_generator.cc",
//				"rtc_base/virtual_socket_server.cc",
//				"rtc_base/weak_ptr.cc",
//				"rtc_base/win/hstring.cc",
//				"rtc_base/win/windows_version.cc",
//				"rtc_base/win/create_direct3d_device.cc",
//				"rtc_base/win/scoped_com_initializer.cc",
//				"rtc_base/win/get_activation_factory.cc",
//				"rtc_base/win32.cc",
//				"rtc_base/zero_memory.cc",
//			],
//			publicHeadersPath: "rtc_core_hdrs"
//		)
	],
	cLanguageStandard: .gnu11,
	cxxLanguageStandard: .gnucxx20
)
